mdbx: refine project directories, CI on github, set of fixes.
2026-07-23 mdbx: update ChangeLog.
2026-07-23 mdbx-cmake: checking needs of linking with `libatomic` for C11 atomics.
2026-07-23 mdbx: comment-out unused `ALLOC_EXACTLY`.
2026-07-23 mdbx: resolve todo in `rkl_clear_and_shrink()`.
2026-07-23 mdbx-tests: disable warning MSVC C4702 "unreachable code" for issues tests.
2026-07-23 mdbx: move `ci` and `exploits` folders into `tests/`.
2026-07-23 mdbx-tests: add `issue_gh0028`.
2026-07-23 mdbx: fix possibility of overflow in `mdbx::slice::safe_middle()`.
2026-07-23 mdbx-tests: add `issue_gh0030`.
2026-07-23 mdbx-tests: add `issue_gh0033`.
2026-07-23 mdbx-tests: initiate tests for issues.
2026-07-23 mdbx:: add missing implementation `mdbx::cursor::estimate(move_operation operation, const slice &key)`.
2026-07-22 mdbx++: fix missing `enable_validation(flags & MDBX_VALIDATION)` inside `mdbx::env::operate_options::operate_options()`.
2026-07-22 mdbx++: fix nested `noexcept()` typo.
2026-07-22 mdbx: fix off-by-one inside `lck_upgrade()`, but unused for now.
2026-07-22 mdbx++: fix UB in case empty array passed to `mdbx::cursor::distribute()`, etc.
2026-07-23 mdbx-ci: add CI-jobs permissions.
2026-07-22 mdbx-tests: fix inconsequential narrow-conversion warnings.
2026-07-22 mdbx: fix minor typos in comments.
2026-07-22 mdbx: fix implicit narrow-conversion warnings.
2026-07-22 mdbx: update ChangeLog.
2026-07-22 mdbx-ci: add MacOS github-workflow.
2026-07-22 mdbx-ci: add Linux github-workflow.
2026-07-22 mdbx-ci: enable verbose of `make`-based builds.
2026-07-22 mdbx: disable extra assertion/check inside atomic `safe64_write()`.
2026-07-22 mdbx-make: link with static library if `MDBX_BUILD_CXX=1` to avoid "undefined reference to `panic_at()`".
2026-07-22 mdbx-make: skip running stochastic script if Bash < 4.4
2026-07-22 mdbx-make: refine `MDBX_BUILD_OPTIONS` to avoid redefinitions/overriding.
2026-07-21 mdbx-tests: fix build by MinGW.
2026-07-22 mdbx: avoid false-positive "maybe uninitialize" warning from old GCC.
2026-07-21 mdbx: refine project directories.
2026-07-21 mdbx-tests: stops filling a testset when DB becomes full in `extra/crunched-delete`.
2026-07-21 mdbx-ci: add Windows/MSVC workflow.
2026-07-21 mdbx-ci: add Windows/MinGW workflow.
2026-07-21 mdbx-ci: add C++/MSVC github-workflow.
2026-07-20 mdbx-ci: add Android github-workflow.
2026-07-20 mdbx-ci: basic CI-script.
2026-07-20 mdbx-tests: using only C++ atomics.
2026-07-20 mdbx-android: fix `pthread_barrier_t` redefinition on modern Android SDKs.
2026-07-22 mdbx-make: add linking with `libatomic`.
2026-07-22 mdbx: refine/fix atomics types for Embarcadero C++ and etc.
2026-07-21 mdbx: rename `DEFINE_ENUM_FLAG_OPERATORS` to `MDBX_DEFINE_ENUM_FLAG_OPERATORS` to allow clear definition aside of buggy MSVC' `DEFINE_ENUM_FLAG_OPERATORS`
2026-07-21 mdbx++: fix/avoid forward references to types for older compilers.