mdbx: LTS checkpoint.
2026-08-30 mdbx: update ChangeLog.
2026-08-30 mdbx: more `MDBX_MAYBE_UNUSED` to avoid warnings while using amalgamated source code.
2026-08-28 mdbx-doc: clarify the description of the `MDBX_opt_rp_augment_limit` adjustment (backport).
2026-08-27 mdbx: fix division underflow in the `default_rp_augment_limit()` (backport).
2026-08-26 mdbx-ci: add workflow on GitHub for windows-ms-clang (backport).
2026-08-29 mdbx: fix `scan4seq_neon()` for LLP4/ARM64-Windows (backport).
2026-08-25 mdbx-windows: fix minor `error: variable 'frame' set but not used` while build mit CLANG/LLVM on Windows (backport).
2026-08-25 mdbx-tests: fix minor `format specifies type 'unsigned int' but the argument has type 'DWORD'` while build by CLANG/LLVM on Windows (backport).
2026-08-25 mdbx-windows: find `llvm-dlltool.exe` to support building with CLANG/LLVM (backport).
2026-08-25 mdbx++: fix `error: attribute 'unlikely' has no effect when annotating an 'if constexpr' statement` for Microsoft CLANG (backport).
2026-08-25 mdbx++: fix `error: explicit instantiation declaration should not be 'dllexport'` for microsoft-corrupted clang.
2026-08-25 mdbx-windows: fix building by Microsoft CLANG for ARM/ARM64/NEON (backport).
2026-08-24 mdbx-windows: fix `unresolved __cpu_indicator_init` while building by ms-clang (backport).
2026-08-09 mdbx-ci: don't use tmpfs on CI to avoid lack of space and `/dev/shm` to avoid interference (backport).
2026-08-29 mdbx-windows: rework/fix `MDBX_WITHOUT_MSVC_CRT=ON` for SEH.
2026-08-29 mdbx: reformat/cosmetics.
2026-08-29 mdbx: fix minor MSVC "conversion" warnings.
2026-08-29 mdbx-ci: fix SourceCraft workflows.
2026-08-25 mdbx-windows: fix `unknown pragma` for ms-clang (backport).
2026-08-29 mdbx-doc: sync README with the `master` branch.
2026-08-17 mdbx-doc: fix 10yo semantic mistake found by AI (backport).
2026-08-15 mdbx-doc: clarify "crash" meaning (backport).
2026-08-11 mdbx: prefer non-portable `fallocate()` to avoid emulation in glibc (backport).
2026-08-08 mdbx-make: increased to 99 the size of a tail log output in case of test failure (backport).
2026-08-08 mdbx-tests: re-fix `copy` testcase for SourceCraft CI (backport).
2026-08-08 mdbx: remove/cleanup the destination in `copy2pathname()` on any error except `MDBX_EEXIST` (backport).
2026-08-08 mdbx-windows: fix loosing of global init and tls-destructors in static library build by MinGW toolchain in particular cases (backport).
2026-08-08 mdbx: more sanity checks of the system page size (backport).
2026-08-08 mdbx-tests: fix looping `copy` testcase in case parallel collision (backport).
2026-08-07 mdbx-tests: fix `copy` testcase for case when destination is already exists (backport).
2026-08-07 mdbx-make: add more duration limits to avoid CI timeouts (backport).
2026-08-07 mdbx: add `MDBX_EEXIST` error code (backport).
2026-08-07 mdbx-make: remove/clean temporary of destination DB-copy (backport).
2026-08-07 mdbx-make: limit duration of test-targets to avoid timeouts on CI (backport).
2026-08-07 mdbx-tests: support `--probe-duration` and `--whole-duration` options in stochastic script (backport).
2026-08-07 mdbx-tests: retry `mdbx_env_info_ex()` in case `MDBX_TXN_OUSTED` to avoid failures in a low-memory conditions (backport).
2026-08-05 mdbx-msvc: add compile-time guard for C11 atomics (backport).
2026-08-07 mdbx: more checks to return `MDBX_OUSTED` instead of `MDBX_BAD_TXN` (backport).
2026-08-05 mdbx-make: update link to the IOArena project source code (backport).
2026-07-14 mdbx-windows: add `/forceInterlockedFunctions-` for ARM64 (backport).
2026-08-05 mdbx-cmake: add `/experimental:c11atomics` for bad MSVC compiler to enable C11 atomics (backport).
2026-08-05 mdbx-cmake: minor refine show compiler options (backport).
2026-08-04 mdbx: fix spilling/accounting for `MDBX_AVOID_MSYNC=ON` (backport).
2026-08-03 mdbx-tests: alter make-targets inside `stochastic` script (backport).
2026-08-03 mdbx: drop minor unnecessary `if()` guard in `cursor_del()` (backport).
2026-08-03 mdbx-doc: minor clarify internal comments (backport).
2026-08-02 mdbx: fix/refine inner cursors refreshing in `cursor_put()` (backport).
2026-08-01 mdbx-tests: initial support of `--with-gdb` in the stochastic script (backport).
2026-08-01 mdbx-windows: enable logging to `stderr` in builds without `MDBX_WITHOUT_MSVC_CRT` (backport).
2026-08-01 mdbx: fix/more inner-cursor invalidation in `cursor_del()` to avoid dangling references to a freed subpage(s) (backport).
2026-07-31 mdbx-tests: provide a destructor for the `nested` testcase to destroy the transaction stack in order (backport).
2026-07-31 mdbx++: drop undue `noexcept` from `buffer::clear_and_reserve()` (backport).
2026-07-31 mdbx++: fix using characher count instead of bytes in `slice` and `buffer` methods (backport).
2026-07-31 mdbx++: fix the handling of `reference` cases in `buffer::reserve()` and `buffer::assign()` (backport).
2026-08-29 mdbx++: don't touch/reserve buffer on zero-sized additions.
2026-07-31 mdbx++: fix assertion in `mdbx::value_result::operator bool()` (backport).
2026-07-31 mdbx-make: fix `run-ut` target (backport).
2026-07-31 mdbx: don't return the new data from `mdbx_replace_ex()` even it the same as present (backport).
2026-07-31 mdbx++: fix templated `extract()`, `replace()` and `replace_reserve()` methods of `mdbx::txn` (backport).
2026-08-29 mdbx-ci: `MDBX_FORCE_ASSERTIONS=1` for Debug builds.
2026-07-31 mdbx: fix the exit status of `mdbx_load` for specific error cases (backport).
2026-07-31 mdbx: fix cond_pair leak in the failure path of `copy_with_compacting()` (backport).
2026-07-31 mdbx: fix rebase/merge mistake in `node_move()` (backport).
2026-07-31 mdbx-cmake: set `--loglevel=notice` for smoke test (backport).
2026-07-31 mdbx-tests: make `--duration` and `--nops` options not mutually exclusive (backport).
2026-07-31 mdbx-cmake: add `--duration=5m` to tests to avoid timeouts on CI (backport).
2026-07-30 mdbx: fix NULL dereference in `walk_pgno()`, which affects `mdbx_chk` (backport).
2026-07-30 mdbx: make `MDBX_ATTRIBUTE_NO_SANITIZE_ADDRESS` global and define `RTHC_ATTRIBUTE_NO_SANITIZE_ADDRESS` for Apple (backport).
2026-07-29 mdbx: skip rthc-registration (reader slot cleanup on thread exit) in LCK-less mode (backport).
2026-07-29 mdbx: skip null-lck slots inside `rthc_thread_dtor()` (backport).
2026-07-29 mdbx-make: add ASAN/UBSAN runtime options (backport).
2026-07-29 mdbx-tests: adds `-fno-sanitize-recover=all` to CFLAGS for UBSAN (backport).
2026-07-29 mdbx: refine/fix tracking and invalidation of the inner part of the sibling cursors inside `cursor_del()` (backport).
2026-07-29 mdbx: move-up pages check inside `cursor_validate()` (backport).
2026-07-29 mdbx-tests: refine core-pattern in stochastic script (backport).
2026-07-28 mdbx-tests: adds ASAN/UBSAN log-output options to stochastic script (backport).
2026-07-28 mdbx-tests: probing and use `-i -p` flags for `tee` in stochastic script (backport).
2026-07-28 mdbx: fix/refine cursor tracking in `node_move()` (backport).
2026-07-27 mdbx: early exit from `spill_cursor_keep()` on frozen page (backport).
2026-07-28 mdbx-tests: refine/fix timeouts for CI on Windows (backport).
2026-08-29 mdbx: update `.gitignore`.
2026-07-26 mdbx++: fix stupid MSVC warning in `mdbx::slice::as_pod()` (backport).
2026-07-26 mdbx: fix extra rdt-unlock in the failure path of `dxb_resize()` (backport).
2026-07-26 mdbx: carefully handle the returned intermediate error codes in `meta_wipe_steady()` (backport).
2026-07-26 mdbx: fix assertion parentheses in `mdbx_txn_renew()` (backport).
2026-07-26 mdbx: fix outer-clone flags in `cursor_clone_slightly()` when source is inner (backport).
2026-07-26 mdbx: track cursors for all modify/touch operations since new spilling could be triggered from `page_alloc()` (backport).
2026-08-28 mdbx: fix spilled-page list memleak on nested transaction abort (backport).
2026-07-25 mdbx++: add missing `mdbx::env::geometry::&operator=()` (backport).
2026-07-26 mdbx-make: fix checking Bash version (backport).
2026-07-23 mdbx: remove spurious assertion inside `spill_cursor_keep()` (backport).
2026-07-23 mdbx++: fix `enable_validation` in the `std::ostream &operator<<(::std::ostream &, const env::operate_options &)` (backport).
2026-07-23 mdbx-cmake: checking needs of linking with `libatomic` for C11 atomics (backport).
2026-07-23 mdbx: fix possibility of overflow in `mdbx::slice::safe_middle()` (backport).
2026-07-23 mdbx: add missing implementation `mdbx::cursor::estimate(move_operation operation, const slice &key)` (backport).
2026-07-22 mdbx++: fix missing `enable_validation(flags & MDBX_VALIDATION)` inside `mdbx::env::operate_options::operate_options()` (backport).
2026-07-22 mdbx: fix minor typos in comments (backport).
2026-07-22 mdbx: fix implicit narrow-conversion warnings (backport).
2026-07-22 mdbx: disable extra assertion/check inside atomic `safe64_write()` (backport).
2026-07-22 mdbx-make: link with static library if `MDBX_BUILD_CXX=0` to avoid "undefined reference to `XYZ`" (backport).
2026-07-22 mdbx-make: skip running stochastic script if Bash < 4.4 (backport).
2026-07-21 mdbx-tests: fix build by MinGW (backport).
2026-07-22 mdbx: avoid false-positive "maybe uninitialize" warning from old GCC (backport).
2026-07-20 mdbx-tests: using only C++ atomics (backport).
2026-07-19 mdbx++: fix missing headroom reservation (backport).
2026-07-18 mdbx++: fix F4 UTF-8 continuation range to 80..8F (backport).
2026-07-18 mdbx: fix mincore_cache shift to iterate from the end (backport).
2026-07-18 mdbx-chk: fix wrong function name in env sync error reporting (backport).
2026-07-15 mdbx-doc: fix minor typo in the README (backport).
2026-07-15 mdbx-apple: fix `mach_port_t` leak inside `mdbx_get_sysraminfo()` (backport).
2026-07-15 mdbx: refine `osal_openfile()` error handling (backport).
2026-07-15 mdbx-windows: fix osal_mresize() section handle leak in unsuccessful case (backport).
2026-07-13 mdbx: fix/avoid float point usage (backport).
2026-07-13 mdbx-doc: add cross-refs to `mdbx_cursor_get_batch()` and `mdbx_cursor_scan()` (backport).
2026-07-13 mdbx: refine keys transformation from/to-double (backport).
2026-08-28 mdbx-ci: backport workflows from the `master` branch.
2026-07-12 mdbx: don't fail transaction on `MDBX_UNABLE_EXTEND_MAPSIZE` (backport).
2026-07-12 mdbx-doc: more minor typos fixing (backport).
2026-07-13 mdbx-windows: fix using `alloca()` (backport).
2026-07-22 mdbx: fix off-by-one inside `lck_upgrade()`, but unused for now (backport).
2026-07-22 mdbx-make: add linking with `libatomic` (backport).
2026-08-11 mdbx-tests: backport updates from the `stable` branch (squashed).
2026-01-21 mdbx++: add `txn::checkpoint()` and a few `env::is_xyz()` methods (backport).
2026-07-22 mdbx-cmake: processing `test` subdirectory regardless of `MDBX_CXX_AVAILABLE` (backport).
2026-07-20 mdbx-android: fix `pthread_barrier_t` redefinition on modern Android SDKs (backport).
2026-07-01 mdbx-make: fix cyclic dependency for `build-test` (backport).
2026-03-08 mdbx-make: fix order of test-targets to avoid removing `src/version.c` (backport).
2026-07-22 mdbx-make: refine `MDBX_BUILD_OPTIONS` to avoid redefinitions/overriding (backport).
2026-07-19 mdbx: more minor typos (backport).
2026-08-10 mdbx-ci: enable CI pipelines on GitHub (backport).
2026-08-10 mdbx-doc: split/restructure ChangeLog (backport).
2026-07-18 mdbx++: backport of allocation-aware changes.
2026-07-18 mdbx++: cleanup spaces after backported changes.
2026-07-18 mdbx: fix build with Valgrind/ASAN after `dfd307797ea3da385961041395dfb7e05aae59c6`.
2026-07-10 mdbx: fix ODR-warnings from modern GCC while both LTO and UBSAN enabled (backport).
2026-07-10 mdbx-make: fix `CTEST_OPT` for `test-memcheck` target (backport).
2026-05-14 mdbx-make: add `valgrind_suppress.txt` to distribution files (backport).
2026-07-10 mdbx-test: move `valgrind_suppress.txt` and corresponding cmake-definitions (backport).
2026-07-11 mdbx-tools: fix 2Gb ram consumption by `mdbx_load` due leak of debug changes (backport).
2026-07-09 mdbx++: add spaceship comparison for `mdbx::slice` and `mdbx::pair` (backport).
2026-07-09 mdbx: squashed important fixes based on AI suggestions (backport).
2026-07-09 mdbx: insignificant fixes based on AI suggestions (squashed, backport).
2026-07-01 mdbx: fix `env_owned_wrtxn()` to avoid by-pass locking in the `MDBX_NOSTICKYTHREADS` mode (backport).
2026-06-21 mdbx: fix `mdbx_cursor_compare()` for a case when cursors binded with the same DBI and same MVCC-snapshot, but different ro-txns (backport).
2026-06-17 mdbx: fix typo in handling `NOMETASYNC` while emit `SYNC_IODQ` (backport).
2026-04-08 mdbx: avoid using `[[maybe_unused]] const` as workaround for MSVC bug (backport).

+